### ISSUE TITLE
Add reverse-mode functions

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#119]
The following are required for IEEE 1788-2015 conformance:
- `sqrRev`, `absRev`, `pownRev`, `sinRev`, `cosRev`, `tanRev`, `coshRev`, `mulRev`, `powRev1`, `powRev2`, `atan2Rev1`, `atan2Rev2`

However, we should provide reverse-mode functions for as many standard functions as we can.

**Comment by dpsanders** [comment]
It's not clear what the best name is for these functions. E.g. [Ibex](http://www.ibex-lib.org/) calls this "backwards mode" and uses names like `bwd_add`:  http://www.ibex-lib.org/doc/interval.html#backward-arithmetic

(Note that Ibex has an LGPL license, so we should not look at the source code, but we can look at the documentation!)

**Comment by dpsanders** [comment]
I think it is best to develop these in a separate package.

**Comment by lbenet** [comment]
> It's not clear what the best name is for these functions. E.g. Ibex calls this "backwards mode" and uses names like bwd_add: http://www.ibex-lib.org/doc/interval.html#backward-arithmetic.

What is the naming convention of these function for Octave's [interval](https://octave.sourceforge.io/interval/) package? 
Cc: @oheim

> I think it is best to develop these in a separate package.

I would rather propose to have them in a submodule, since their application is too tight to `ValidatedNumerics.jl`.

**Comment by oheim** [comment]
> What is the naming convention of these function for Octave's interval package?

I have used the function names from the IEEE standard, see https://octave.sourceforge.io/interval/package_doc/Function-Names.html#tab_003arequired_002dreverse_002dfunctions

I have merged `mulRev` and `mulRevToPair` into a single function, which may return either 1 or 2 values.

Also, you can find reverse operations in Gaol under the name “relational arithmetic”, see https://sourceforge.net/p/gaol/code/HEAD/tree/trunk/doc/gaol.pdf?format=raw

**Comment by dpsanders** [comment]
There are a few of these inverse functions (which is, actually, what they really are) implemented in https://github.com/dpsanders/IntervalConstraintProgramming.jl/blob/master/src/reverse_mode.jl. 

Indeed, these functions are only used (as far as I can tell) for constraint propagation.
Since their flavour is rather different, and at a higher level, in some sense, than other functions in `ValidatedNumerics.jl`, I definitely think they belong in a separate package (as, in fact, do the root-finding methods).

Once Pkg3 is a reality, it will (or, rather, should) be easier to group closely-related packages together in a bundle. 

Closing this for now.
