### ISSUE TITLE
Move root-finding functions to a separate repo?

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#121]
And rename this one to `IntervalArithmetic.jl`?

**Comment by lbenet** [comment]
I am in favor of *not* doing them. For the time being, the repo hasn't grown too much, so root-finding methods can still be part of it. As for changing the name, I really like `ValidatedNumerics`; I think the repo (as reflected by the current name) is a bit more than only Interval Arithmetics.

**Comment by dpsanders** [comment]
I was just starting to worry that it's not clear what the scope of the package should be. For example, should there be things to plot intervals?

**Comment by lbenet** [comment]
Including some plotting utilities would indeed be nice, as well as including other utilities (optimization, etc). This will simply make the package more robust and of wider scope. 

As for the name, I really think it speaks for itself. Searching for "interval arithmetic julia" in google yields `ValidatedNumerics.jl` as the first entry, and duckduckgo.com has it as the second one.

Finally, there is some people out there using it. Changing the name (or the definition of the basic types, #124) has a cascade of consequences, which I think we may save.
