### ISSUE TITLE
Add setdiff for IntervalBox

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#138]
We need setdiff for IntervalBox. Do you know how to implement this, @lbenet ?

**Comment by lbenet** [comment]
setdiff?

**Comment by dpsanders** [comment]
The [http://mathworld.wolfram.com/SetDifference.html](set difference).

**Comment by dpsanders** [comment]
A \ B = {x \in A: x \notin B}

**Comment by lbenet** [comment]
Thanks for the reference. Isn't `setdiff` the same as `cancelminus`? In any case, let's avoid the use of `\` for that function, since in Julia `\` has already a well-defined meaning.

**Comment by dpsanders** [comment]
For an Interval it may be the same, but I don't understand `cancelminus`, so I couldn't say ;)

For an IntervalBox it is more complicated. Indeed it is not clear what the answer should be: an IntervalBox (and if so which one) or a union of IntervalBoxes. Well, it is clear -- it should be the union. But this seems to be tricky to do in general.

**Comment by lbenet** [comment]
> For an Interval it may be the same, but I don't understand cancelminus, so I couldn't say ;)

(From our docstrings) Return the unique interval c such that b+c=a. So, for an `Interval` it indeed is the complement.

>For an IntervalBox it is more complicated. Indeed it is not clear what the answer should be: an IntervalBox (and if so which one) or a union of IntervalBoxes. Well, it is clear -- it should be the union. But this seems to be tricky to do in general. 

Considering `a=IntervalBox(0..2, 0..2)` and `b=IntervalBox(0..1, 0..1)` for concretness, I agree that we are looking for the union in the sense of a tuple (not the hull) of `IntervalBox`s. We need to require that each element of the tuple has no intersection with any other different element, except maybe if it is the border. I can't really define it now, but for the example, a possibility is that `c = cancelminus(a,b)` returns 
`tuple(IntervalBox(1..2, 0..1), IntervalBox(0..1, 1..2), IntervalBox(1..2, 1..2)`. So we preserve some "cartesianity" of each of the elements, the rule being that you fix all but one dimension, and there you use `cancelminus`. And the rest you somehow treat it similarly.

I'm thinking on bricks in 2 or more dimensions...

**Comment by dpsanders** [comment]
Done in #143 for 2D `IntervalBox`es.
The code gives the pattern for higher dimensions, but it is not clear how to implement it in a generic way. This may require generated functions (`@generate`)?

**Comment by lbenet** [comment]
I also guess that `@generate` is the way to go for higher dimensions...

**Comment by dpsanders** [comment]
I found a better way to do it; implemented in #144 .
