### ISSUE TITLE
Add support for DoubleDouble

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#139]
We should add support for making intervals with `Double{Float64}` inside; these are numbers with twice the precision of `Float64` from the [`DoubleDouble.jl`](https://github.com/simonbyrne/DoubleDouble.jl) package.

**Comment by dpsanders** [comment]
This should actually need more work on the side of the `DoubleDouble.jl` package; in principle this should now be trivial from the point of view of `ValidatedNumerics.jl`?

**Comment by lbenet** [comment]
I'll take a look on the package. I guess that if you have something like `Double <: Number` or `Double <: AbstractFloat` this should pretty straightforward.

**Comment by dpsanders** [comment]
Currently, with the development branch (`refactor`) of `DoubleDouble`, the following works:
```
julia> using DoubleDouble

julia> a = Double(pi)
Double(3.141592653589793, 1.2246467991473532e-16)
 - value: 3.1415926535897932384626433832795

julia> b = Interval(a)
[3.14159, 3.1416]

julia> typeof(b)
ValidatedNumerics.Interval{DoubleDouble.Double{Float64}}
```
However, arithmetic does not:
```

julia> b + b
ERROR: MethodError: `get_rounding_raw` has no method matching get_rounding_raw(::Type{DoubleDouble.Double{Float64}})
 in with_rounding at rounding.jl:51
 [inlined code] from /Users/dpsanders/.julia/v0.4/ValidatedNumerics/src/intervals/macros.jl:38
 in + at /Users/dpsanders/.julia/v0.4/ValidatedNumerics/src/intervals/arithmetic.jl:102
```
since `DoubleDouble` does not (yet?) have rounding operations.

**Comment by lbenet** [comment]
The fact that we can not implement directed rounding is bad. Can it be implemented relying on `BigFloat`s (precision 128 or so)?

**Comment by lbenet** [comment]
I mean, some sort of `big128` macro, just as `big53`...

**Comment by dpsanders** [comment]
That is certainly possible, but removes the usefulness of `DoubleDouble`, which is its speed (100x or 1000x compared to BigFloat)

**Comment by dpsanders** [comment]
In any case, this is really an issue with `DoubleDouble`, not with `ValidatedNumerics`, which should just work once rounding is implemented for `DoubleDouble`, so closing.
