### ISSUE TITLE
Merge Newton intervals

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#151]
```
f(x) = (x-1)*(x^2 - 2)^2
newton(f, -5..5)
```
gives
```
11-element Array{ValidatedNumerics.Root{Float64},1}:
 Root(Interval(-1.4142135665081526, -1.4142135649672456), :unknown)
 Root(Interval(-1.4142135649672454, -1.4142135634263384), :unknown)
 Root(Interval(-1.4142135631647694, -1.4142135617186085), :unknown)
 Root(Interval(-1.414213561199032, -1.414213560011549), :unknown)  
 Root(Interval(1.0, 1.0), :unique)                                 
 Root(Interval(1.4142135594939003, 1.4142135603051051), :unknown)  
 Root(Interval(1.4142135603051054, 1.4142135611163102), :unknown)  
 Root(Interval(1.414213562075777, 1.4142135622486425), :unknown)   
 Root(Interval(1.4142135622967371, 1.4142135624904715), :unknown)  
 Root(Interval(1.4142135625359786, 1.41421356273629), :unknown)    
 Root(Interval(1.4142135627362902, 1.4142135629366013), :unknown)  
```
We should make sure the intervals are overlapping (I think I changed this at some point), then order them and take the union of neighbouring ones.

**Comment by lbenet** [comment]
Do you understand the asymmetry of the result? I mean, there are four proposed roots for `-sqrt(2)` whereas there are six for the positive one!

I think the roots are still sorted; I like the idea of merging overlapping intervals.

**Comment by lbenet** [comment]
Incidentally, `-sqrt(2.0)` is only contained in the 3rd root displayed, and `sqrt(2.0)` is only contained in the 9th. So, why do the others are displayed?

**Comment by dpsanders** [comment]
I guess because the Newton operator applied to them is unable to prove that there is no root in that interval with Float64 precision.

**Comment by dpsanders** [comment]
Done in #156.
