### ISSUE TITLE
Is this package applicable to deal with complex data

### ISSUE THREAD

**Issue by The-Kite-Runner** [dpsanders/ValidatedNumerics.jl#157]
Excuse me, I just wonder that whether this package can be applied to to deal with complex data or not.

**Comment by dpsanders** [comment]
Yes, you can use complex intervals, i.e. objects with a real and an imaginary part, both of which are intervals:

```
julia> a = (3..4) + (5..6)*im
[3, 4] + [5, 6]*im

julia> a * a
[-27, -9] + [30, 48]*im
```
Is that what you meant?

**Comment by The-Kite-Runner** [comment]
Yes, thanks a lot~
