### ISSUE TITLE
Load error: Pkg.add("ValidatedNumerics")

### ISSUE THREAD

**Issue by The-Kite-Runner** [dpsanders/ValidatedNumerics.jl#158]
Hi, is this package not available for windows users?

----
Pkg.add("ValidatedNumerics")

INFO: Installing CRlibm v0.2.3
INFO: Installing Calculus v0.1.15
INFO: Installing FixedSizeArrays v0.2.1
INFO: Installing ForwardDiff v0.2.0
INFO: Installing NaNMath v0.2.1
INFO: Installing ValidatedNumerics v0.4.3
INFO: **Building CRlibm**
===============================[ ERROR: CRlibm ]================================

LoadError: **Package not currently available on Windows**
while loading C:\Users\123\.julia\v0.4\CRlibm\deps\build.jl, in expression starting on line 15

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CRlibm had build errors.

 - packages with build errors remain installed in C:\Users\123\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("CRlibm")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of ValidatedNumerics
INFO: Use `Pkg.update()` to get the latest versions of your packages

**Comment by lbenet** [comment]
Seems that the problem is related with [CRlibm.jl](https://github.com/dpsanders/CRlibm.jl). Could you please open an issue there?

**Comment by The-Kite-Runner** [comment]
Okay, thanks
