### ISSUE TITLE
`derivative` has no method matching derivative<::Function>

### ISSUE THREAD

**Issue by The-Kite-Runner** [dpsanders/ValidatedNumerics.jl#159]
Nearly all the examples in the documentation run normally, but the [Root finding](http://dpsanders.github.io/ValidatedNumerics.jl/root_finding/), shown below.

![newtonderivativematching](https://cloud.githubusercontent.com/assets/18660347/16618256/fea6c5d6-43ba-11e6-9f34-ff2634a14624.png)

![krawczykderivative](https://cloud.githubusercontent.com/assets/18660347/16618259/01ed32b6-43bb-11e6-948d-8f83e2fe546b.png)

![findrootderivative](https://cloud.githubusercontent.com/assets/18660347/16618262/069fb108-43bb-11e6-84a2-ef08d5b83842.png)

OS: windows 8.1 64bit
Julia: 0.4.6

Thanks

**Comment by lbenet** [comment]
It runs fine for me. Note that all root finding methods have been moved to a submodule, so you have to include it.

```julia
julia> using ValidatedNumerics, ValidatedNumerics.RootFinding

julia> f(x) = x^2 - 2
f (generic function with 1 method)

julia> newton(f, @interval(-5,5))
2-element Array{ValidatedNumerics.RootFinding.Root{Float64},1}:
 ValidatedNumerics.RootFinding.Root{Float64}([-1.41422, -1.41421],:unique)
 ValidatedNumerics.RootFinding.Root{Float64}([1.41421, 1.41422],:unique)  

julia> krawczyk(f, @interval(-5,5))
2-element Array{ValidatedNumerics.RootFinding.Root{Float64},1}:
 ValidatedNumerics.RootFinding.Root{Float64}([-1.41422, -1.41421],:unique)
 ValidatedNumerics.RootFinding.Root{Float64}([1.41421, 1.41422],:unique)  
```

**Comment by The-Kite-Runner** [comment]
thanks for your timely reply, I have included it from the start, but failed, shown below. The package has
been updated, and I don't know why julia can't recognize the submodules.

![submodule](https://cloud.githubusercontent.com/assets/18660347/16624310/c74883b8-43d3-11e6-90ac-3ca7c7a43ba7.png)

![submodule1](https://cloud.githubusercontent.com/assets/18660347/16624708/54c1d5c8-43d4-11e6-87e9-4957ff743bc2.png)

**Comment by dpsanders** [comment]
The `RootFinding` module is only on the `master` branch of the package for the moment.
You can get this with

```julia
Pkg.checkout("ValidatedNumerics")
```

**Comment by The-Kite-Runner** [comment]
I have checked the package with `checkout`, but nothing changed. However, the submodule has been called successfully. Thank you~

![checkoutvalidatednumerics](https://cloud.githubusercontent.com/assets/18660347/16647608/9c6c45b4-4462-11e6-8834-3e35751a2457.png)

**Comment by dpsanders** [comment]
Actually this did update the package to the latest version ("Pulling ValidatedNumerics latest master"), even.
