### ISSUE TITLE
Unable to run basic arithmetic operation `*`

### ISSUE THREAD

**Issue by The-Kite-Runner** [dpsanders/ValidatedNumerics.jl#160]
In [the usage demo](http://dpsanders.github.io/ValidatedNumerics.jl/usage/), it shows that: 

> Basic arithmetic operations (+, -, *, /, ^) are defined for pairs of intervals in a standard way (see, e.g., the book by Tucker): the result is the smallest interval containing the result of operating with each element of each interval. That is, for two intervals XX and YY and an operation ∘∘

however, when I mulitplied two intervals, an error occurred, shown as below:

![multiply](https://cloud.githubusercontent.com/assets/18660347/16680661/d8d3dd62-4522-11e6-9845-9160215d7a70.png)

**Comment by dpsanders** [comment]
To create an interval, you just use the `...`:

```julia
julia> a = 1..2; b = 1..3
[1, 3]

julia> a * b
[1, 6]
```

**Comment by dpsanders** [comment]
As you see in the error message, it treats `[1..2]` as an array containing a single interval:
```julia
julia> a = [1..2]
1-element Array{ValidatedNumerics.Interval{Float64},1}:
 [1, 2]
```

The `...` is just a shorthand for `a = @interval(1, 2)`.
