### ISSUE TITLE
@interval and .. operator not equivalent to Interval

### ISSUE THREAD

**Issue by gmoutsin** [dpsanders/ValidatedNumerics.jl#162]
I pasted bellow the commands and the returned strings in Julia terminal that generates the error.

julia> set_bigfloat_precision(2048)
2048

julia> x = BigFloat(1)/10
1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e-01

julia> d = x^10000
1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007734e-10000

julia> Interval(-d,d)
[-1.00001e-1000, 1.00001e-10000]₂₀₄₈

julia> @interval(-d,d)
[-4.94066e-324, 4.94066e-324]

julia> -d..d
[-4.94066e-324, 4.94066e-324]

**Comment by dpsanders** [comment]
The problem is here:
> julia> set_bigfloat_precision(2048)

As stated in the documentation (although probably not carefully or prominent enough), you must use `setprecision(Interval, 2048)`, not `set_bigfloat_precision` directly.

Please feel free to submit a Pull Request to make the documentation clearer!

**Comment by dpsanders** [comment]
Note that you can also use the (undocumented?) `@biginterval` to generate an interval of `BigFloat`s.

**Comment by gmoutsin** [comment]
I missed this point in documentation and I must admit that it is not an obscure one. What I don't understand with this is the following.

If I set precision with 
`julia> set_bigfloat_precision(2048)`
then what is the precision of a float? Is it 2048 or the standard machine precision? Do I have to set it separately? I am asking because I need also to use float numbers in the same script.

**Comment by dpsanders** [comment]
This is subtle and could definitely be better explained in the docs.

The point is that you should avoid (i.e., not use) `set_bigfloat_precision` when you are doing interval calculations. This is used "under the hood" when you do `setprecision(Interval, 2048)`, so the precision of `BigFloat`s will change. However, there are other things that must be changed along with it, e.g. the value of `pi` that is used in trigonometric functions, to avoid recalculating it all the time.

To change back to using `Interval{Float64}`, you do `setprecision(Interval, Float64)`.
Using `@interval` will automatically create an interval with the current interval precision, either `Float64` or `BigFloat` with the current precision. You can check the current precision with `precision(Interval)`.

If you want more explicit control, you can use `@floatinterval` and `@biginterval`; the latter will create a `Interval{BigFloat}` with the current `BigFloat` precision.

Please don't hesitate to say if this is not clear.  Indeed, it's not even clear if it's a sensible idea to have this flexibility (also called "awkwardness") with regards to changing the precision. If you have ideas for better / clearer names for these functions, or for how precision works, please say!

The motivation for this complicated setup is basically as follows. `Float64`s are *much* (maybe 1000 times) faster than `BigFloat`s, so `Float64`s are regarded as the default. But sometimes there is simply no alternative to using intervals with higher precision. Furthermore, there are algorithms in which it is useful to have a kind of dynamic precision, so it needs to be possible to write generic code in which changing the precision *type* (from `Float64` to `BigFloat`) should be possible without rewriting the code (and without introducing type instability...). I am by no means certain, however, that the current way is sensible.

There are also a few alternatives in the works for higher, but not arbitrary, precision, e.g. `ArbFloats.jl` and `DoubleDouble.jl`. The former, in particular, seems to be close to being usable and should provide a very compelling alternative to `BigFloat`.
