### ISSUE TITLE
Julia rounding problem

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#165]
https://github.com/JuliaLang/julia/issues/17926

This is very bad news for ValidatedNumerics.jl, although until now there doesn't seem to be an issue with our tests? cc @lbenet

**Comment by lbenet** [comment]
For v0.5-dev, we disabled testing ITF-1788 in b9e61b6. Yet, running them locally I see no problem, though they still take too long... I just pushed #166; let's see how travis reacts...

**Comment by dpsanders** [comment]
We do not seem to have an issue with this Julia problem, since we don't do rounding with operations on literals.
