### ISSUE TITLE
Eliminate extra `convert` when creating an interval

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#170]
``` julia
julia> Interval{BigFloat}(0.1)
[0.0999999, 0.100001]₂₅₆

julia> showall(ans)
Interval(9.999999999999999999999999999999999999999999999999999999999999999999999999999914e-02, 1.000000000000000000000000000000000000000000000000000000000000000000000000000002e-01)
```

This is doing `convert(Interval{BigFloat}, 0.1)`.
Probably it should instead just do the equivalent of `Interval{BigFloat}(BigFloat(0.1))`.

This can be achieved by adding the following:

``` julia
(::Type{Interval{T}}){T}(arg) = Interval(convert(T, arg))
```

where the `convert` to type `T` is done directly on the argument.

**Comment by lbenet** [comment]
I guess you are right. I thought that `convert` methods were equivalent to the constructors.

**Comment by dpsanders** [comment]
Again reflects the idea that it should be *possible* to use the floating-point value if you *really* want to, without extra conversion.

However, I'm not sure what to do about e.g.
```
julia> (::Type{Interval{T}}){T}(arg) = Interval(convert(T, arg))

julia> Interval{BigFloat}(1//3)
Interval(3.333333333333333333333333333333333333333333333333333333333333333333333333333348e-01, 3.333333333333333333333333333333333333333333333333333333333333333333333333333348e-01)
```

**Comment by lbenet** [comment]
Was this corrected by #188? In master I get the following,
```julia
julia> Interval{BigFloat}(1//3)
Interval(3.333333333333333333333333333333333333333333333333333333333333333333333333333305e-01, 3.333333333333333333333333333333333333333333333333333333333333333333333333333348e-01)

julia> isthin(ans)
false
```

**Comment by lbenet** [comment]
... which seems to be correct!

**Comment by dpsanders** [comment]
But it also does the `convert` for `Float64` arguments, which I would argue is incorrect.

**Comment by lbenet** [comment]
> But it also does the convert for Float64 arguments, which I would argue is incorrect.

I guess what you mean is:
```julia
julia> Interval{Float64}(1//3)
Interval(0.3333333333333333, 0.33333333333333337)
```
which is correct (in terms of yielding an interval containing `1//3`) but does not yield `Interval{Rational{Int}}`. Is that it?

The issue originates in specifying the type parameter; without it, everything works nicely.

Somehow, by specifying the type parameter, instead of calling a method defined by us, it calls a default convert method:
```julia
julia> @which Interval{Float64}(1//3)
(::Type{T}){T}(arg) at sysimg.jl:53

julia> @which Interval(1//3)
julia> @which Interval(1//3)
(::Type{ValidatedNumerics.Interval}){T<:Real}(a::T) at /Users/benet/.julia/v0.5/ValidatedNumerics/src/intervals/intervals.jl:30
```
