### ISSUE TITLE
Unstable calculations with ValidatedNumerics?

### ISSUE THREAD

**Issue by gmoutsin** [dpsanders/ValidatedNumerics.jl#176]
I have a title with a question mark because I cannot really find the cause of the problem, so it may not even be in ValidatedNumerics.

In short, I do some calculation that I expect to converge but they blow up. Doing the same calculation using just numbers works.

I tried to write a minimal setup where the problem appears but because I am not sure what is going on exactly my setup is not as minimal asI hoped. I have uploaded it [here](https://github.com/gmoutsin/ValNumIssue).

The script `HenonConst.jl` uses `ValidatedNumerics` and `HenonConstNoIntervals.jl` doesn't. They do the exactly the same calculations (as far as I understand), but the results differ. The file `HenonCoeffsList.jl` just has the coefficients required for the computation.

**Comment by dpsanders** [comment]
This is usually what happens when intervals are used with standard numerical methods. What does the calculation do? For example, for finding fixed points or roots, there is an interval version of the Newton(-Raphson) method; using the standard method but putting in intervals does indeed lead to useless results like this.

**Comment by gmoutsin** [comment]
Thanks for the reply David. I am trying to get the Stokes constant of the separatrix splitting of the Henon map. I was doing the same in July for an other instance of the Henon map and I am trying to rewrite my script to be more efficient (my old one is stupid and slow). However I did manage to get a result back in July. I did have problems initially but I somehow solved them.

After reading your reply, I run again my old script and it doesn't work any more! I updated Julia to 0.5 in the meantime and I got the latest version of Validated numerics. I assume something broke in the meantime. Now it gives nonsensical results.

The computation is very straight forward. I choose fix `n` and choose an approximation of the point `W^-(t-n)` (say `p`) and an approximation of the point `W^+(t+n)` (say `q`), these are the stable and the unstable separatrix respectively. They both satisfy `W(t+1) = Henon(W(t))`.

Then I apply the map `n` times on `p` and the inverse map `n` times on `q` and get the points `P` and `Q` respectively. Then the difference `Q-P` approximates well the difference of the two separatrices `W^+(t) - W^-(t)`. I don't think I can use the Newton method for this.

**Comment by lbenet** [comment]
As David writes, it is a subtle issue to use the same algorithm which works with real/complex numbers and with intervals. Intervals grow in a way to ensure that the true answer is contained in the interval; usually, the results are too pessimistic, so adapted algorithms are required.

Aside from Interval Arithmetics, have you look at [this paper](http://cosweb1.fau.edu/~jmirelesjames/standardMapNotes.pdf) (but for the standard map)? It seems to me that it could be useful for what you want to calculate.

**Comment by gmoutsin** [comment]
Thank you for the paper. It is interesting. Regardless I need to do what I described. I have proved that the method converges (mathematically) and I want to compute a couple of constants as examples. The method works well numerically, I just would like to trace the numerical error also.

I understand that the intervals need to grow so it is not guaranteed that the method will converge, however I did this few months ago.  What actually worries me in this case is that my old script does not work any more.

**Comment by dpsanders** [comment]
Do you mean that the same script you posted worked on Julia 0.4 but not 0.5? Or maybe with a different version of the package? If so, we should definitely look carefully at that.

**Comment by gmoutsin** [comment]
Yes, I have also this problem. I have done this of an instance of the Henon map and I thought of doing the same for an other instance and use this opportunity to write a better script. Yesterday I run it again and it does not work.

I uploaded that script in the folder [old](https://github.com/gmoutsin/ValNumIssue/tree/master/old). It is not written properly but it used to produce correct results. I have uploaded also the results I got for imaginary part 50 and 100 in the respective files. The structure of the files is `steps [tab] midpoint of the real part [tab] width of the real interval [tab] midpoint of the imaginary part [tab] width of the imaginary interval`.

The constant is actually imaginary and the real part of the approximation serves as a way to get the mathematical error of the approximation.

Now running the same script again gives huge intervals as result (but at least not infinite). I am not sure exactly which version I used to do the calculations but it was around late June and it was a fresh installation.

**Comment by gmoutsin** [comment]
I solved my problem by using the Horner form for all polynomial involved. Now the error gets tracked efficiently. I spent some time looking at my old script but I couldn't really pinpoint something and since it is a mess I decided to pretend it does not exist. I guess something changed but since I am not affected any more I am closing this issue. Thanks for your replies.

**Comment by dpsanders** [comment]
Glad to hear that you solved the problem. We are happy that the package is being used and tested in different contexts so please keep raising issues and/or PRs.
