### ISSUE TITLE
Current state of windows compatibility?

### ISSUE THREAD

**Issue by hwatson** [dpsanders/ValidatedNumerics.jl#179]
When I installed ValidatedNumerics, I got the following warning:

_WARNING: CRlibm not properly installed; falling back to use MPFR.
        This is currently the default on Windows. The package should still
        work correctly, but will be slower._

The package works for creating intervals and basic operations like +,-,*,/ as intended.
However, I've just tried to use transcendental/trigonometric functions for the first time, but I get an error, e.g. for exp:

_LoadError: error compiling exp: could not load library "C:\Users\Harry Watson\.julia\v0.5\CRlibm\src\../deps/src/crlibm-1.0beta4/libcrlibm"
The specified module could not be found._

If I look in the CRlibm directory, there is indeed no such library (the configure/make files haven't been executed), but running Pkg.build("CRlibm") only returns:

_INFO: Building CRlibm
WARNING: On Windows, CRlibm currently just wraps MPFR, and so is slow_

...and then nothing changes.

Any help would be greatly appreciated!

**Comment by lbenet** [comment]
Do you get the same if you checkout to the "master" branch, i.e., `Pkg.checkout("ValidatedNumercs")`?

Other ideas @dpsanders ?

**Comment by dpsanders** [comment]
@hwatson You are possibly the first person to try this; sorry it's not working.

Could you try
```julia
using CRlibm
CRlibm.shadow_mpfr()
```
This should define functions like `exp` just to "shadow" the corresponding `BigFloat` functions.

To get the library truly up and running on Windows, all it requires is for someone with experience of Windows compilers to make a shared library that can then be downloaded. Tony Kelman gave a talk or workshop at JuliaCon about this.

**Comment by dpsanders** [comment]
I thought `CRlibm.shadow_mpfr()` was automatically run on Windows. If not, this should definitely be fixed.

**Comment by dpsanders** [comment]
In any case, this is definitely an issue with `CRlibm`, rather than with `ValidatedNumerics` per se.

**Comment by dpsanders** [comment]
I think I have found the problem. Could you please try the following branch: 

```
Pkg.checkout("CRlibm", "windows_mpfr")
```

Then try (from a new Julia session) `using ValidatedNumerics` as usual.

**Comment by hwatson** [comment]
@dpsanders 

I tried:
```
using CRlibm
CRlibm.shadow_mpfr()
```
and I received:
_LoadError: UndefVarError: shadow_mpfr not defined_

And I tried:
_Pkg.checkout("CRlibm", "windows_mpfr")_

And received a long error that began with:
_LoadError: GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)_

I removed and re-added CRlibm and ValidatedNumerics before trying either of these (in a new Julia session).

**Comment by dpsanders** [comment]
Ah sorry, I think you will need

```
Pkg.checkout("CRlibm")
Pkg.checkout("CRlibm", "windows_mpfr")
```

**Comment by dpsanders** [comment]
If that doesn't work, please try manually changing directory to `v0.5/CRlibm` in your `.julia` directory, and doing 

```julia
git pull 
git checkout windows_mpfr
```
there.

**Comment by hwatson** [comment]
Doesn't seem to have had any impact... running the git commands in the directory asserts that my branch is up-to-date with 'origin/windows_mpfr'

And running the checkout commands just tells me:
_INFO: Checking out CRlibm master...
INFO: Pulling CRlibm latest master...
INFO: No packages to install, update or remove
INFO: Checking out CRlibm windows_mpfr...
INFO: Pulling CRlibm latest windows_mpfr...
INFO: No packages to install, update or remove_

And then I still get the same error trying to exponentiate an interval. 

(I have to go for about an hour now, I'll check back ASAP)

**Comment by dpsanders** [comment]
Fixed in CRlibm (on master, and release in process).
