### ISSUE TITLE
Add first and last convenience functions

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#180]
... that return the `lo` and `hi` fields of an interval.

**Comment by lbenet** [comment]
I just noticed that we have the functions `infimum(a)` and `supremum(a)`, which return respectively `a.lo` and `a.hi`. Do you want to rename these? Or do you want to add these aliases to use as iterators?

**Comment by dpsanders** [comment]
Renamed to `inf` and `sup` in #267.
