### ISSUE TITLE
Move to StaticArrays.jl

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#183]
From `FixedSizeArrays.jl`

**Comment by dpsanders** [comment]
Done in the `static_arrays` branch. This passes tests on 0.5 and nearly does on 0.6.

**Comment by dpsanders** [comment]
Now passing on the `fix_radius` branch!  cc @lbenet 

Note that the `StaticArrays` package requires Julia >= 0.5.

**Comment by lbenet** [comment]
As you wrote elsewhere, I think we should simply drop supporting Julia 0.4, which would also imply to tag a new version.

**Comment by dpsanders** [comment]
Done in #245.
