### ISSUE TITLE
Inverse odd powers of intervals are incorrect

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#187]
```
julia> x = -27..27
[-27, 27]

julia> x^(1//3)
[0, 3.00001]
```

cc @lbenet

**Comment by dpsanders** [comment]
Also for `x^(1//3)`

**Comment by lbenet** [comment]
I think this is correct, and some of the ITF1788 test suite precisely address this. For instance, `@fact Interval(-0.1, 0.5) ^ Interval(0.1, 0.1) --> Interval(0.0, 0x1.ddb680117ab13p-1)`.

Though it is surprising, I think the result is consistent, since
```julia
julia> (-27.0)^(1/3)
ERROR: DomainError:
 in nan_dom_err at ./math.jl:196 [inlined]
 in ^(::Float64, ::Float64) at ./math.jl:355
```

**Comment by dpsanders** [comment]
I think this is because in the ITF1788 suite, there is no way of expressing rational numbers.
For rationals we should be able to do this correctly.

**Comment by lbenet** [comment]
I think the result is independent of the ITF1788 suite, but is somewhere in the Floating point standard:
```julia
julia> (-27.0)^(1//3)
ERROR: DomainError:
 in nan_dom_err at ./math.jl:196 [inlined]
 in ^(::Float64, ::Float64) at ./math.jl:355
 in ^(::Float64, ::Rational{Int64}) at ./rational.jl:378

```

**Comment by dpsanders** [comment]
This is a type-stability issue:
while `(-27.0)^(1//3)` is a well-defined real number,  `(-27.0)^(1//2)` would be complex.
