### ISSUE TITLE
Faster, but less accurate, integer powers

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#190]
We could provide, even by default, a faster version of integer powers using ~a custom version of~`Base.power_by_squaring`, e.g. something like the following (NB: this version works only for odd powers):

```julia
function mypower(a::Interval, n::Integer)
         lo = setrounding(Float64, RoundDown) do
           Base.power_by_squaring(a.lo, n)
       end

         hi = setrounding(Float64, RoundUp) do
           Base.power_by_squaring(a.hi, n)
       end
       Interval(lo, hi)
       end

julia> @time mypower(a, 3)
  0.000007 seconds (133 allocations: 7.781 KB)
[-0.00100001, 0.0270001]

julia> @time a^3
  0.000035 seconds (56 allocations: 2.273 KB)
[-0.00100001, 0.0270001]
```

**Comment by dpsanders** [comment]
Note that this is guaranteed to give a correct enclosure, since `power_by_squaring` just uses `*`, which has correct rounding.

However, it usually gives a (slight) overestimate, e.g.
```julia 
julia> a^3
Interval(-0.0010000000000000002, 0.027000000000000014)

julia> mypower(a, 3)
Interval(-0.0010000000000000002, 0.027000000000000017)
```

**Comment by dpsanders** [comment]
Very strange:
```
julia> setrounding(Float64, RoundDown) do
       x = a.lo
       x * x * x * x * x
       end
-1.0000000000000003e-5
```

**Comment by dpsanders** [comment]
This is the correctly-rounded result:
```
julia> setprecision(BigFloat, 1000)
1000

julia> x = big(a.lo)
-1.00000000000000005551115123125782702118158340454101562500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e-01

julia> setrounding(BigFloat, RoundDown) do
       x^5
       end
-1.00000000000000027755575615628916592078702721848043759006154036409810439169414738887804167353333224309663542172658333034712873250211953753939018749738829993000129761298390668741934428870463863404455068846481927165722330893878196881457975919715863710734993219375610351562500000000000000000000000000000000e-05
```

**Comment by dpsanders** [comment]
Apparently `Base.power_by_squaring` will not cut it: 
```
julia> setrounding(Float64, RoundDown) do
       ((((x*x)*x)*x)*x), (x*(x*(x*(x*x)))), Base.power_by_squaring(x, 5)
       end
(-1.0000000000000003e-5,-1.0000000000000003e-5,-1.0e-5)
```

**Comment by dpsanders** [comment]
I don't think this can work in a naive way, since `x*x` has already lost information.
One possible solution would be `power_by_squaring` using intervals:

```
julia> x = @interval -0.1
Interval(-0.1, -0.09999999999999999)

julia> Base.power_by_squaring(x, 5)
Interval(-1.0000000000000006e-5, -9.99999999999999e-6)
```

**Comment by dpsanders** [comment]
I don't think this can work in a naive way, since `x*x` already loses information -- it rounds in the "wrong" direction. This could be done using intervals:

```julia
function mypower(x::Interval, n::Int)
  lo = Interval(x.lo)
  hi = Interval(x.hi)
  hull( Base.power_by_squaring(lo, n), Base.power_by_squaring(hi, n) )
end
```

**Comment by dpsanders** [comment]
With this definition:
```
julia> x = -0.1..0.3
Interval(-0.1, 0.30000000000000004)

julia> @time mypower(x, 5)
  0.000007 seconds (21 allocations: 448 bytes)
Interval(-1.0000000000000006e-5, 0.002430000000000003)

julia> @time x^5
  0.000035 seconds (56 allocations: 2.273 KB)
Interval(-1.0000000000000004e-5, 0.002430000000000002)
```

**Comment by dpsanders** [comment]
Note that there seems to be a bug with `^` for `BigFloat` in Julia 0.5:
```
julia> x = -0.1..0.3
[-0.100001, 0.300001]

julia> mypower(x, 70)
[9.99999e-71, 2.50316e-37]

julia> x^70
[0, 2.50316e-37]
```

**Comment by dpsanders** [comment]
The following seems to be a general solution (that could be *slightly* improved for efficiency):
```
function mypower{T}(x::Interval{T}, n::Int)
    
    isempty(x) && return x
    
    if iseven(n) && zero(T) ∈ x

        return hull(zero(x), 
                    hull(Base.power_by_squaring(Interval(mig(x)), n), 
                        Base.power_by_squaring(Interval(mag(x)), n))
            )
        
    else
        
      return hull( Base.power_by_squaring(Interval(x.lo), n), 
                    Base.power_by_squaring(Interval(x.hi), n) )
        
    end
        
end
```

**Comment by lbenet** [comment]
I agree that it would be nice to have a faster implementation, but I think we still have to impose that it yields not only correctly rounded results, but also as tight as possible intervals. 

The problem (slowness) of the current implementation is that it needs to convert to `BigFloats` where correctly rounded is assured, perform there `^`, and then convert back to `Float64`. As far as I recall, that was the reason for `big53` to be used there.

Have you tested `mypower` against the ITF1788 suite?

**Comment by dpsanders** [comment]
There is (as far as I understand) no way to have correct rounding and tight intervals without using MPFR. However, the loss of tightness from using `mypower` is "small".

I haven't tested it against the ITF1788 suite, for the same reason.

**Comment by lbenet** [comment]
I agree with you, it seems there is no way around MPFR to get correct rounding. 

If `mypower` yields *almost* tight intervals, I don't expect that it will pass the ITF1788 test suite. I'll try to spend some time on this this afternoon.

**Comment by dpsanders** [comment]
We should test `mypower` with a more relaxed version of the ITF1788 tests, where only "approximately equal", rather than "exactly equal", is used.

**Comment by dpsanders** [comment]
Implemented and exported as the function `pow` in the `fast_pow` branch.

Then just use 
```julia
^(x::Interval{Float64}, n::Integer) = pow(x, n)
```
to use this by default whenever integer powers of intervals are taken.

**Comment by dpsanders** [comment]
Implemented in the `fast_pow` branch.

**Comment by dpsanders** [comment]
Done in #208.
