### ISSUE TITLE
Rename `interior` to `isinterior`

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#219]
Since returns a `Bool`.

**Comment by dpsanders** [comment]
Do we want to do this for 0.7? The names of the other comparison functions don't seem to be so in need of the `is` at the start.

**Comment by lbenet** [comment]
That's up to you; if we do, just drop me a line, so I change the syntax in the ITF1788 tests.

**Comment by dpsanders** [comment]
Done in #233

**Comment by dpsanders** [comment]
Fixed by #233
