### ISSUE TITLE
Bigfloat constants depend on initial precision

### ISSUE THREAD

**Issue by lbenet** [dpsanders/ValidatedNumerics.jl#24]
Following our discussion in #20, there are some constants that depend on the precision set at the beginning (which is 53), e.g. `big_pi_interval`. Their value influences the output from `sin` in a somewhat uncontrolled manner.
This issue is to keep in mind this and corrected it.

**Comment by dpsanders** [comment]
Just to record that we have agreed that it would be nice to have a dictionary or type where all this information is stored and which is updated when e.g. the precision is set.

**Comment by dpsanders** [comment]
Will be fixed by #25
