### ISSUE TITLE
Put ∅ (`emptyinterval`) into the `interval_parameters` type

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#33]
And change its precision along with `set_interval_precision`

**Comment by lbenet** [comment]
`emptyinterval(T)`, and other special intervals, are currently parametrically defined, and are fully functional and conforming the standard. At the moment, I think there is no real necessity for including it in `interval_parameters`. Do you have a specific case where this will be helpful?

**Comment by dpsanders** [comment]
The idea was to be able to type `∅` and have it return the `emptyinterval` with the current precision. Maybe this is not necessary / useful, since really one just wants to be able to test something like
`a == ∅`, which already works.

**Comment by lbenet** [comment]
In addition, there is now `isempty(a)` (and other related functions), which precisely tests if `a == emptytest(eltype(T))` holds.
