### ISSUE TITLE
Add option to display intervals as `3 ± 0.1`

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#39]
Implement @lbenet's suggestion in a comment on #35, we should implement a display option to show the interval `[2.9, 3.1]` as `3.0 ± 0.1`, using `midpoint_radius`.

This could be a global option in the `IntervalParams` type, and/or a keyword argument to `show`.

**Comment by lbenet** [comment]
Just to be very clear: I think this is worth specially for the midpoint_radius representation, not necessarily in general.

**Comment by dpsanders** [comment]
Fixed by #115.
