### ISSUE TITLE
Implement loose vs. strict evaluation

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#51]
As pointed out by Warwick Tucker, it is necessary to be able to turn on and off "loose evaluation" (in which the part of an interval outside the domain of a function is ignored, i.e. for  `sqrt([-1,1])`, and "hard evaluation", in which an exception is thrown.

This is because fixed-point results *do not hold* with loose evaluation.
This is implemented, for example, in [filib](http://www2.math.uni-wuppertal.de/~xsc/software/filib.html)

It will be necessary to have a global switch, and then two new types of exception, `TotalDomainError` and `PartialDomainError`, for example.

EDIT: When there is no overlap with the domain of the function and loose evaluation is in place, we should return the empty interval. However, it is not clear how to handle this in the context of multidimensional intervals.

**Comment by lbenet** [comment]
I agree; incidentally, great micro-curse and discussion!

The global switch essentially should constrain the interval with the functional domain for "loose evaluation" (for `log` it is [0,Inf]), as we already do. For "hard evaluation" we should not constrain the interval (or take the trivial intersection with [-Inf,Inf]), and let Julia throw a `DomainError()` if there are problems.

Or are you thinking on something more sofisticated?

**Comment by dpsanders** [comment]
This will be possible (I believe) via decorations, required by the IEEE 1788 standard #67.
