### ISSUE TITLE
Implement our own standard functions library

### ISSUE THREAD

**Issue by lbenet** [dpsanders/ValidatedNumerics.jl#53]
This issue is a simple reminder, also born in the discussion with Warwick Tucker. 

I think we should implement our own standard functions library as others do. I think the usual approach is to use some precomputed values (probably in extended precision) and Taylor expand around them, which allows us to control the error. I think this is reasonably simple for the trigonometric functions, but much subtler for `exp` or `log`...

**Comment by dpsanders** [comment]
As we have discussed, I don't think we should/can go down this route.
With CRlibm we have a lot of the necessary functions.

**Comment by lbenet** [comment]
Thanks for closing this; I fully agree to stick to the CRlibm, and only in case of necessity, implement whatever is needed (e.g., `tanh`).
