### ISSUE TITLE
Usage of CRlibm, or what about ValidatedNumerics.jl for v0.3?

### ISSUE THREAD

**Issue by lbenet** [dpsanders/ValidatedNumerics.jl#59]
In my last [commit](https://github.com/dpsanders/ValidatedNumerics.jl/commit/f1b268377934281c79f1ad029472c87e3c0929be), I am using some of the functions from [CRlibm.jl](https://github.com/dpsanders/CRlibm.jl), in order to get the correct rounding. That library requires version 0.4-. Obviously, tests for v0.3 are failing; the problem in travis seems to be related with something related to github (SSL certificates...?) and v0.5. (On v0.4-rc3 two tests fail on my machine, which seem to yield the correct results from the REPL..., but travis is not checking it.)

We may stop supporting v0.3, which seems to me a bit too early (if so, we should tag a new version, and inform about this decision). Another possibility is to relax the requirement of julia 0.4- for CRlibm. Shall I add a line so travis checks version 0.4? What do you think we should do?

**Comment by dpsanders** [comment]
CRlibm uses two features that are only available in 0.4 (call overloading and dispatch on rounding mode types) and I don't think it's worth adding 0.3 support for it. 

Many packages are already releasing new minor versions that work only on 0.4 and the stuff with CRlibm is a breaking change anyway, so I would be happy to tag a final 0.1.3 for v0.3 and then tag a new version 0.2 that only supports v0.4 (which looks like it will be released in about a week).

**Comment by lbenet** [comment]
If CRlibm needs really 0.4, I agree that there is no interest in supporting 0.3 further. I think we should do it straight away, adding somewhere (README.md?) a brief note which mentions CRlibm and the fact that that version (0.1.3) does not satisfy thoroughly the ITF1788 tests.

Regarding #56, I'm coming forward; `sin` and `cos` are ready, and I'm dealing with `tan`.

**Comment by dpsanders** [comment]
Let's tag 0.1.3 as the last version supported by Julia v0.3.

Could you please add an update to `NEWS.md` specifying what you have changed?

**Comment by lbenet** [comment]
Are referring to #56? Sure, I'll take care of this today, including [adding](https://github.com/dpsanders/ValidatedNumerics.jl/pull/56#commitcomment-13621266) `CRlibm.jl` to `REQUIRE`.

**Comment by dpsanders** [comment]
No, for v0.1.3 it's #55 only

**Comment by dpsanders** [comment]
But for #56 you should add a different entry in news.md with the heading 0.2.0 saying what's changed, please!

**Comment by lbenet** [comment]
Thanks for clarifying. I'll do it later

**Comment by lbenet** [comment]
One more clarification: The entries for 0.2.0, should they be added at the same time as that for 0.1.3, or should I wait until 0.1.3 is tagged to add them?

**Comment by dpsanders** [comment]
I would add the 0.1.3 ones in a new  PR right now, and add the 0.2 ones in
#56. That way they will be automatically incorporated at the right moment!

**Comment by lbenet** [comment]
As for the first version 0.4 compatible *only*, do you really mean to tag it as 0.2? There was a plan to get to 0.2 (#31), which doesn't seem to me to be complete...

**Comment by dpsanders** [comment]
It's not complete no, we'll just push the other stuff to 0.3. (Although CRlibm was part of 0.2.)

In any case, the change in rounding behaviour is sufficient to bump to 0.2 in my opinion, since it's a breaking change.

**Comment by dpsanders** [comment]
And the new dependency on the new package `CRlibm`.

**Comment by lbenet** [comment]
I have updated #60 mentioning the use of your `CRlibm.jl`. I also included the dependency on `CRlibm` in #56 in `REQUIRE` and adapted `.travis.yml` to test only julia 0.4 and the nightly version.

**Comment by dpsanders** [comment]
Thanks.
