### ISSUE TITLE
What happens with intervals of `Float32` and `Float16`?

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#64]
Maybe we should allow these, or do they already work?
What happens with rounding in these cases?

**Comment by lbenet** [comment]
See this [comment](https://github.com/dpsanders/ValidatedNumerics.jl/pull/56#discussion_r41946254)

**Comment by dpsanders** [comment]
We have decided not to support these for the moment. In particular, `CRlibm` only works with `Float64`, and this is what's required for the IEEE 1788 standard.
