### ISSUE TITLE
Improve API documentation

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#73]
All user-facing functions should have examples. These should ideally be tested with something like `jldoctest`.

**Comment by lbenet** [comment]
I am not familiar with what you mean, but I agree with `jldoctest`. 
Incidentally, the standard also requires a good documentation.

**Comment by dpsanders** [comment]
I meant that functions that the user would want to use (as opposed to internal functions) should have short examples of usage.

**Comment by dpsanders** [comment]
Closing in favor of #105
