### ISSUE TITLE
Inverse of zero interval

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#74]
These doesn't seem right:
```julia
julia> a = @interval(-0.0, 0.0)
[-0.0, 0.0]

julia> 1/a
∅

julia> a = @interval(0)
[0.0, 0.0]

julia> 1/a
∅
```

**Comment by dpsanders** [comment]
Is this defined in the standard?

**Comment by lbenet** [comment]
Why do you think that this is not right? 
The display of the first case is something related to Julia itself (I was the author of that PR), and the examples do follow the ITF1788 test suite.

**Comment by dpsanders** [comment]
I was thinking that `1/[0.,0.]` should give `[Inf, Inf]`.
But indeed, this is disallowed by the standard.
