### ISSUE TITLE
Add aliases for names from the IEEE Standard 1788

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#75]

**Comment by lbenet** [comment]
What do you mean exactly? I think this could go in the documentation...

**Comment by dpsanders** [comment]
I meant defining functions with the same names in the standard that just refer to the corresponding Julia names. I will do this.

**Comment by lbenet** [comment]
I think it is better to make explicit those subtleties in the documentation, but stick to the names that we have chosen, or simply change them. The standard doesn't require to have the same names, but to have the functionality. I also think it is better to have one way of referring to the functions, than many. Once said this, a counter example induced by me, is related with `round`...

**Comment by dpsanders** [comment]
Actually, in this case I don't agree.

It is a Julia package and should definitely use Julia names, so we should not change the names.

But, on the other hand, someone coming from outside who wants to use the package should not necessarily be expected to use those names if they're used to the names from the standard, for example from the Octave package. I don't see any harm in exporting the additional names.

**Comment by lbenet** [comment]
Somewhere I recall that this kind of discussion came up (julia-users list, or elsewhere); the outcome was to minimize the name possibilities of the functions. 
That's the reason it should appear clearly in the documentation, both for the help and in the package documentation.

**Comment by oheim** [comment]
IMHO you should use unique function names and stick to the names which are common to Julia users. This will be less confusing for your users when they mix interval computations and non-interval computations. As @lbenet says, the standard does not require to use particular names for the functions. You may use operators or other names.

That's also what has been done in the Octave package. The function names are taken from Octave functions. Only functions that did not exists before got the name from the standard document.

You can document the standard's function name in the function's documentation to make it clear, which functionality it implements. Additionally there is a [function index](http://octave.sourceforge.net/interval/package_doc/Function-Names.html) for the Octave package, which should help anybody who knows the standard, but is unfamiliar with Octave. You could add something similar to your documentation.

**Comment by dpsanders** [comment]
I have implemented an aliasing mechanism in #79 
Currently, all it does is look up the IEEE name and return the corresponding Julia name.
In my opinion, this is more useful and pleasant than looking things up in the documentation.
These days any such kind of look-up can easily be done by the programming environment.

The current syntax is
```julia
@alias convexHull
```
which gives the result
```julia
:hull
```
indicating that the corresponding Julia function is `hull`.
It also works the other way round: `@alias hull` will give `:convexHull`. 

The list of aliased names is in a new source file. It's not yet complete.

**Comment by dpsanders** [comment]
Closing as probably unnecessary.
