### ISSUE TITLE
Is there a way of plotting results?

### ISSUE THREAD

**Issue by FavioVazquez** [dpsanders/ValidatedNumerics.jl#81]
I was watching Tucker's presentations about the subject and he has pictures like 

![screenshot from 2015-11-03 23 08 52](https://cloud.githubusercontent.com/assets/10162068/10930003/e533351e-827f-11e5-827b-7c3264b3815e.png)

![screenshot from 2015-11-03 23 16 01](https://cloud.githubusercontent.com/assets/10162068/10930109/e3bb1e94-8280-11e5-9901-30e22f952f1b.png)

The second one is not generated by serious calculation but I remember him saying that the first one is. So I was wondering if there's a way of plotting what's happening when computing the calculations, lets say root finding, and that the change in the interval is reflected in the plot and that kind of stuff? 

I'm planning of using this library to do a project in numerical methods at PCF-UNAM and it would be important for the presentation to have this kinds of graphs. I just don't want to do it by hand, but if there's no other way I'll do it.

In the same line of thought, can you suggest a problem that I can solve using this? I was thinking of showing my classmates and teacher's this library and theory that I find fascinating but if you can suggest a physical problem, not to hard, to solve using this, and the implemented functions it has, it could be really interesting. 

Thanks.

**Comment by lbenet** [comment]
> I was wondering if there's a way of plotting what's happening when computing the calculations, lets say root finding, and that the change in the interval is reflected in the plot and that kind of stuff?

There is no plotting function, so I suggest you develop it and send a PR :-) 
For both root-finding methods, we have a `debug` option, which provides lots of information on what is being done; I would begin there, though I think that you might want something a bit different.

> In the same line of thought, can you suggest a problem that I can solve using this? I was thinking of showing my classmates and teacher's this library and theory that I find fascinating but if you can suggest a physical problem, not to hard, to solve using this, and the implemented functions it has, it could be really interesting. 

There are *lots* of nice questions, aside from enlarging the coverage of our package. Some ideas include looking for periodic orbits of dynamical systems, some linear algebra questions (eigenvalues or matrix inversion), rigorous bounds in the integration of functions, rigorous integration/evolution of ODEs, questions about stability, etc. Once said this, I should add that this is out of the scope of "an issue" for the package, so if you are interested you should contact us directly by email.

I'm closing this issue.

**Comment by dpsanders** [comment]
I'm not sure what you mean by creating the figures "by hand".
These figures are obtained using the bisection method, drawing the calculated range over the given interval as a box, and using different colors to denote different stages of bisection.

As @lbenet said, this is a good exercise!

The second figure just checks whether 0 is or is not inside the box, and colors it accordingly.

To draw rectangles like this, one solution is the `PyPlot.jl` package. You can see a working example here from which you can just use the `draw_rectangle` function:

http://nbviewer.ipython.org/urls/dl.dropbox.com/s/nauexpdblerlypi/pi%20from%20area.ipynb

**Comment by FavioVazquez** [comment]
I was wondering if there were some native plotting functions for intervals that do that plots automatically. But now I see your point. By hand I meant just that, plotting color coded rectangles with your plot. Yes I've seen that with PyPlot, but I'll try to find my way of doing it with Gadfly, I'm trying to make the project just using Julia for the time, but if complicated plots appear I'll just switch to PyPlot. Thanks again!

**Comment by dpsanders** [comment]
To just draw rectangles, it might be better to use `Compose.jl`, which is the plotting library that `Gadfly` uses. However, unfortunately it is not very well documented.

**Comment by FavioVazquez** [comment]
I'll check that out. Thanks!

**Comment by dpsanders** [comment]
If you're still interested, there is now built-in plotting of 2D `IntervalBox`es using the `Plots.jl` package.
