### ISSUE TITLE
Spanish documentation?

### ISSUE THREAD

**Issue by FavioVazquez** [dpsanders/ValidatedNumerics.jl#82]
I know English is the language of science and programming, but would you find a Spanish translation of the docs helpful? I could do it all and create a PR to close this issue. I think it may help some people, you could expand this package to non-English speakers and the more documentation the merrier. 

I'm planning of doing it anyway because I'll make a presentation in Spanish of this package, just introductory to my classmates and teachers, and I was wondering if you would find that interesting or you're not considering it now.

**Comment by dpsanders** [comment]
Maintaining documentation in one language is difficult enough... If you would like to help with the (English) documentation, that would be very welcome.
