### ISSUE TITLE
Trying to use the package in a function 

### ISSUE THREAD

**Issue by FavioVazquez** [dpsanders/ValidatedNumerics.jl#83]
Hi, I've been playing around with the package and I've created a simple code to obtain and plot the roots of a function. I want to create a function that receives a function and then do this things:

```
using ValidatedNumerics, PyPlot

x = linspace(-1.0,1.0,100)
f = 0.375 - 3.75x.^2 + 4.375x.^4
f1(x) = 0.375 - 3.75x.^2 + 4.375x.^4
z = find_roots_midpoint(f1,-1,1)[1]
plot(x,f)
plot(z,zeros(z),"rs")
axhline(y=0.0, color="black")
``` 

This is just a simple example for the 4th order Legendre polynomial. This code produces the next plot:

![issue1](https://cloud.githubusercontent.com/assets/10162068/11329130/44727116-915d-11e5-8414-1b248cf681b5.png)

I want a function that implements all of that steps and do this for an arbitrary function defined bu the user, but I haven't been able to do so. I don't know if this is the right place to ask but I didn't find a mailing list or a gitter chat.

Thanks.

**Comment by dpsanders** [comment]
This is not really the right place to ask. There is, in fact, a gitter chat: https://gitter.im/dpsanders/ValidatedNumerics.jl

Feel free to open a PR to add the gitter badge to the README.

**Comment by dpsanders** [comment]
What problem are you having in implementing the function? Remember that in Julia you can easily send a function as an argument to another function ("functions are first-class objects"):

```julia
f1(x) = 3x^2 + 2x
f2(x) = x 

g(f, x) = 2*f(x)

g(f1, x)
g(f2, x)

julia> g(f1, 1)
10

julia> g(f2, 1)
2
```

**Comment by dpsanders** [comment]
Perhaps the problem you are having is applying an arbitrary function `f` to all elements of a vector `x`. A simple way to do this is `map(f, x)`. Another way is an array comprehension:  `[f(xx) for xx in x]`

**Comment by dpsanders** [comment]
Nice example and idea, by the way!

**Comment by FavioVazquez** [comment]
Hello, thanks for your help @dpsanders, I'll be sending you an email with the functions I manage to create. I think they are interesting and useful.
