### ISSUE TITLE
`make_interval` is `convert`  

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#95]
`make_interval` is just `convert` in disguise and should be `convert`ed to `convert`.

E.g. `make_interval(::Type{Float64}, x::Real)` should be `convert(::Type{Interval{Float64}}, x::Real)`

Unfortunately this is hard to read. Maybe possible to do with a macro?

**Comment by lbenet** [comment]
I agree that `make_interval` is *essentiallly* a disguised `convert` which uses `@round` or `@thin_round` at some point. Maybe we can simply avoid the step of using `make_interval` by adding its methods as `convert` methods.

The only case that may rest there is `make_interval with two (numeric) arguments, which is used when `@interval` is called.

**Comment by dpsanders** [comment]
Done in #98.
