### ISSUE TITLE
Use `ForwardDiff` package

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#99]
We should use the `ForwardDiff` package instead of our own for automatic differentiation, since it is efficient, well-tested, and has Jacobians already implemented.

**Comment by lbenet** [comment]
I fully agree (and was thinking about proposing this!).

I have been playing lately with techniques to improve range estimation, and I've been using our implementation. While it works fine and does what we need, it lacks the possibility of dealing with many degrees of freedom (independent variables), which is something that we are aiming to.

**Comment by dpsanders** [comment]
#101
